/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "brand/brand-primary": "#f97316",
        "brand/brand-neutrals-white": "#f5f5f4",
        "brand/brand-background": "#e7e5e4",
        "brand/brand-primary-fade": "#ffcfae",
        "brand/brand-neutrals-black": "#0c0a09",
        "brand/brand-primary/brand-primary-1": "#fef1e8",
        "brand/brand-primary/brand-primary-2": "#feddc7",
        "brand/brand-primary/brand-primary-3": "#fcc39b",
        "brand/brand-primary/brand-primary-4": "#fba76c",
        "brand/brand-primary/brand-primary-5": "#fa8c40",
        "brand/brand-primary/brand-primary-6": "#f97316",
        "brand/brand-primary/brand-primary-7": "#d46213",
        "brand/brand-primary/brand-primary-8": "#b15210",
        "brand/brand-primary/brand-primary-9": "#8e420d",
        "brand/brand-primary/brand-primary-10": "#70340a",
        "brand/brand-neutrals-black/brand-neutrals-black-1": "#ffffff",
        "brand/brand-neutrals-black/brand-neutrals-black-2": "#fdfdfd",
        "brand/brand-neutrals-black/brand-neutrals-black-3": "#f5f5f5",
        "brand/brand-neutrals-black/brand-neutrals-black-4": "#f0f0f0",
        "brand/brand-neutrals-black/brand-neutrals-black-5": "#dbdada",
        "brand/brand-neutrals-black/brand-neutrals-black-6": "#c2c2c2",
        "brand/brand-neutrals-black/brand-neutrals-black-7": "#929190",
        "brand/brand-neutrals-black/brand-neutrals-black-8": "#61605f",
        "brand/brand-neutrals-black/brand-neutrals-black-9": "#4e4c4b",
        "brand/brand-neutrals-black/brand-neutrals-black-10": "#302f2e",
        "brand/brand-neutrals-black/brand-neutrals-black-11": "#292727",
        "brand/brand-neutrals-black/brand-neutrals-black-12": "#1f1e1d",
        "brand/brand-neutrals-black/brand-neutrals-black-13": "#0c0a09",
        "brand/brand-neutrals-white/brand-neutrals-white-1": "#ffffff",
        "brand/brand-neutrals-white/brand-neutrals-white-2": "#ffffff",
        "brand/brand-neutrals-white/brand-neutrals-white-3": "#ffffff",
        "brand/brand-neutrals-white/brand-neutrals-white-4": "#fefefe",
        "brand/brand-neutrals-white/brand-neutrals-white-5": "#fefefd",
        "brand/brand-neutrals-white/brand-neutrals-white-6": "#fdfdfc",
        "brand/brand-neutrals-white/brand-neutrals-white-7": "#fbfbfa",
        "brand/brand-neutrals-white/brand-neutrals-white-8": "#f9f9f8",
        "brand/brand-neutrals-white/brand-neutrals-white-9": "#f8f8f7",
        "brand/brand-neutrals-white/brand-neutrals-white-10": "#f7f7f6",
        "brand/brand-neutrals-white/brand-neutrals-white-11": "#f6f6f5",
        "brand/brand-neutrals-white/brand-neutrals-white-12": "#f6f6f5",
        "brand/brand-neutrals-white/brand-neutrals-white-13": "#f5f5f4",
        "brand/brand-background/brand-background-1": "#fdfcfc",
        "brand/brand-background/brand-background-2": "#f9f9f9",
        "brand/brand-background/brand-background-3": "#f5f4f3",
        "brand/brand-background/brand-background-4": "#f0efee",
        "brand/brand-background/brand-background-5": "#ebeae9",
        "brand/brand-background/brand-background-6": "#e7e5e4",
        "brand/brand-background/brand-background-7": "#c4c3c2",
        "brand/brand-background/brand-background-8": "#a4a3a2",
        "brand/brand-background/brand-background-9": "#848382",
        "brand/brand-background/brand-background-10": "#686767",
        "brand/brand-primary-fade/brand-primary-fade-1": "#fffaf7",
        "brand/brand-primary-fade/brand-primary-fade-2": "#fff3ec",
        "brand/brand-primary-fade/brand-primary-fade-3": "#ffeadc",
        "brand/brand-primary-fade/brand-primary-fade-4": "#ffe1cc",
        "brand/brand-primary-fade/brand-primary-fade-5": "#ffd8bd",
        "brand/brand-primary-fade/brand-primary-fade-6": "#ffcfae",
        "brand/brand-primary-fade/brand-primary-fade-7": "#d9b094",
        "brand/brand-primary-fade/brand-primary-fade-8": "#b5937c",
        "brand/brand-primary-fade/brand-primary-fade-9": "#917663",
        "brand/brand-primary-fade/brand-primary-fade-10": "#735d4e",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
